query getSeasonShows($season: String!) {
  allContent(
    type: ["FashionShowV2"]
    first: 1000
    filter: { season: { slug: $season } }
  ) {
    Content {
      title
      slug
      ... on FashionShowV2 {
        photosTout {
          ... on Image {
            url
          }
        }
      }
    }
  }
}
