# fly.toml file generated for neferpitou on 2022-10-01T14:02:55+01:00

app = "neferpitou"
kill_signal = "SIGINT"
kill_timeout = 6
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  AIESEC_ENDPOINT = "https://gis-api.aiesec.org/graphql"
  AIESEC_TOKEN="15c0929b1e3425cde7cda73687d58a0ab2a6c1a1c533b03b3ba196c08be870bf"
  GOOGLE_SPREADSHEET_ID = "1nWaT1iyOUhFgd7Vn9xKBrI0UG24D3HpHtAqSh4XnJoE"
  TELEGRAM_CHAT_ID = "--1001231499058, -584375582"
  TELEGRAM_LINK = "https://api.telegram.org/bot1632133071:AAHU5m-1iKfNZBGy2yLR8x_z_awT9HnKM8I"
  ZIAD_CHAT_ID = "513915705"
  MCVP= "6cfb82fbb6be1c16658eb4ef45c5a348864b0bf2ff6fa637e9710e997dbf2e64"
  HUBSPOT_API_KEY="eu1-647e-fb18-4039-958b-f59c75ffb726"
  HUBSPOT_DEV_KEY="eu1-ea63-8953-4abb-9cb0-a6c8d0ac417e"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
