query getSeasonShows($season: String!) {
  allContent(
    type: ["FashionShowV2"]
    first: 1000
    filter: { season: { slug: $season } }
  ) {
    Content {
      id
      url
      title
      slug
      ... on FashionShowV2 {
        instantShow
        brand {
          name
        }
        photosTout {
          ... on Image {
            url
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
